#!/bin/sh
# fail on any error
set -e

# newrelic, variables passed from the cloud formation templates.
# This variables are used in the agent config ( newrelic.ini file)
NEWRELIC_ENABLED=${NEWRELIC_ENABLED}
NEWRELIC_DAEMON_HOST=${NEWRELIC_DAEMON_HOST:-""}
NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME:-""}
NEWRELIC_LICENSE=${NEWRELIC_LICENSE:-""}

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"


