version: '2'

services:
    app:
        container_name: test-app
        image: test-app:latest
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
            args:
                - BASE_IMAGE=${APP_BASE_IMAGE}
                - NEWRELIC_VERSION=${NEWRELIC_VERSION}
        environment:
            NEWRELIC_ENABLED: ${NEWRELIC_ENABLED}
            NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
            NEWRELIC_LICENSE:  ${NEWRELIC_LICENSE}
            NEWRELIC_USE_HACK: ${NEWRELIC_USE_HACK}